[general]
import = ["~/.config/alacritty/themes/themes/solarized_dark.toml"]

[font]
normal = { family = "MesloLGS Nerd Font" }
bold = { family = "MesloLGS Nerd Font" }
italic = { family = "MesloLGS Nerd Font" }

[window]
padding.x = 3
padding.y = 10
