[language-server.cspell]
command = "cspell-lsp"
args = ["--stdio"]

[[language]]
name = "markdown"
formatter = { command = "dprint", args = [ "fmt", "--stdin", "md" ] }
auto-format = true
language-servers = ["markdown-oxide", "cspell"]
