[language-server.cspell]
command = "cspell-lsp"
args = ["--stdio"]

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20           # set max completion results len for each group: words, snippets, unicode-input
feature_words = false                # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = true        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

[[language]]
name = "markdown"
formatter = { command = "dprint", args = [ "fmt", "--stdin", "md" ] }
auto-format = true
language-servers = ["markdown-oxide", "cspell", "scls"]
